# Generated by Django 6.0.7 on 2026-07-15 06:34

import autodialer.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('paused', 'Paused'), ('finished', 'Finished'), ('overdue', 'Overdue'), ('canceled', 'Canceled')], db_index=True, default='new', max_length=20)),
                ('connect_to', models.CharField(max_length=128)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('campaign_pace', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('billable_account', models.CharField(max_length=128)),
                ('caller_id', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_dispatched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('i_customer', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('external_data', models.JSONField(blank=True, default=dict)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_file', models.FileField(upload_to=autodialer.models.campaign_audio_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='autodialer.campaign')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('queued', 'Queued'), ('called', 'Called'), ('failed', 'Failed'), ('paused', 'Paused'), ('invalid', 'Invalid')], db_index=True, default='new', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='autodialer.campaign')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='autodialer.externaluserprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='autodialer.externaluserprofile'),
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_call_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('call_tag', models.CharField(blank=True, max_length=128)),
                ('tracking_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=32)),
                ('account_id', models.CharField(blank=True, max_length=128)),
                ('caller_id', models.CharField(blank=True, max_length=128)),
                ('destination', models.CharField(blank=True, max_length=32)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('previous_tracking_id', models.CharField(blank=True, max_length=128)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reason_code', models.IntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('call_type', models.CharField(blank=True, max_length=64)),
                ('connect_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('playback_requested_at', models.DateTimeField(blank=True, null=True)),
                ('playback_completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='autodialer.campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='autodialer.contact')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='autodialer.externaluserprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['owner', 'status'], name='autodialer__owner_i_2ddddb_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['campaign', 'status'], name='autodialer__campaig_2cd54c_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['owner', 'phone_number'], name='autodialer__owner_i_59d133_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('owner', 'campaign', 'phone_number'), name='unique_contact_per_campaign_phone'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['owner', 'status'], name='autodialer__owner_i_05761f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['owner', 'name'], name='autodialer__owner_i_22238d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['owner', 'scheduled_at'], name='autodialer__owner_i_7ed36c_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['campaign', 'status'], name='autodialer__campaig_abc39c_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['contact', 'status'], name='autodialer__contact_e93ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['tracking_id'], name='autodialer__trackin_3b9d62_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['external_call_id'], name='autodialer__externa_ea8a99_idx'),
        ),
    ]
