# Generated by Django 6.0.7 on 2026-08-09 06:23

import uuid

import django.db.models.deletion
from django.db import migrations, models

import autodialer.models


class Migration(migrations.Migration):
    dependencies = [
        ("autodialer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("preparing", "Preparing"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "csv_file",
                    models.FileField(
                        max_length=255,
                        upload_to=autodialer.models.contact_import_upload_to,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_import_jobs",
                        to="autodialer.campaign",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_import_jobs",
                        to="autodialer.externaluserprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactImportFailure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.PositiveIntegerField()),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                ("row_data", models.JSONField(blank=True, default=dict)),
                ("failure_reason", models.TextField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="autodialer.contactimportjob",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contactimportjob",
            index=models.Index(
                fields=["owner", "status"], name="autodialer__owner_i_1b3905_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactimportjob",
            index=models.Index(
                fields=["owner", "campaign", "status"],
                name="autodialer__owner_i_caa259_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactimportfailure",
            constraint=models.UniqueConstraint(
                fields=("job", "row_number"), name="unique_contact_import_failure_row"
            ),
        ),
    ]
